server:
  port: 8003

spring:
  application:
    name: customer-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/erureka/
   instance:
      hostname: localhost
