server:
  port: 7878
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
      
spring:
  application:
      name: ZUUL-API
  
#http://localhost:8031/customer-service/customer-api/customer 
      
zuul:
  prefix: /customer-service
  routes:
    CUSTOMER-SERVICE:
      path: /customer-api/**
      service-id: CUSTOMER-SERVICE
    PRODUCT-SERVICE: 
      path: /product-api/**
      service-id: PRODUCT-SERVICE
    RESTAPI: 
      path: /restapi-api/**
      service-id: RESTAPI